# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Commentator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField()),
                ('why_cricket', models.TextField()),
                ('fav_cricket_moments', models.TextField()),
                ('previuosly_provided_commentary', models.TextField()),
                ('photo', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='commentary',
            name='commentator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentary', to='commentator.Commentator'),
        ),
    ]
